server:
  port: 8080
  ssl:
    enabled: ${SSL_ENABLED:false}
  forward-headers-strategy: native

spring:
  session:
    store-type: redis
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PASSWORD}
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DB_URL:default-jdbc-url}
    username: ${DB_USERNAME:default-username}
    password: ${DB_PASSWORD:default-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security.oauth2: TRACE
    org.springframework.security: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.session: DEBUG
    org.springframework.jdbc: DEBUG